SRCPATH := mbedtls-3.6.2/library

MBEDTLS_SOURCES +=								 			\
			$(SRCPATH)/aes.c                                 \
			$(SRCPATH)/aesce.c                               \
			$(SRCPATH)/aesni.c                               \
			$(SRCPATH)/aria.c                                \
			$(SRCPATH)/asn1parse.c                           \
			$(SRCPATH)/asn1write.c                           \
			$(SRCPATH)/base64.c                              \
			$(SRCPATH)/bignum.c                              \
			$(SRCPATH)/bignum_core.c                         \
			$(SRCPATH)/bignum_mod.c                          \
			$(SRCPATH)/bignum_mod_raw.c                      \
			$(SRCPATH)/block_cipher.c                        \
			$(SRCPATH)/camellia.c                            \
			$(SRCPATH)/ccm.c                                 \
			$(SRCPATH)/chacha20.c                            \
			$(SRCPATH)/chachapoly.c                          \
			$(SRCPATH)/cipher.c                              \
			$(SRCPATH)/cipher_wrap.c                         \
			$(SRCPATH)/cmac.c                                \
			$(SRCPATH)/constant_time.c                       \
			$(SRCPATH)/ctr_drbg.c                            \
			$(SRCPATH)/debug.c                               \
			$(SRCPATH)/des.c                                 \
			$(SRCPATH)/dhm.c                                 \
			$(SRCPATH)/ecdh.c                                \
			$(SRCPATH)/ecdsa.c                               \
			$(SRCPATH)/ecjpake.c                             \
			$(SRCPATH)/ecp.c                                 \
			$(SRCPATH)/ecp_curves.c                          \
			$(SRCPATH)/ecp_curves_new.c                      \
			$(SRCPATH)/entropy.c                             \
			$(SRCPATH)/entropy_poll.c                        \
			$(SRCPATH)/error.c                               \
			$(SRCPATH)/gcm.c                                 \
			$(SRCPATH)/hkdf.c                                \
			$(SRCPATH)/hmac_drbg.c                           \
			$(SRCPATH)/lmots.c                               \
			$(SRCPATH)/lms.c                                 \
			$(SRCPATH)/md5.c                                 \
			$(SRCPATH)/md.c                                  \
			$(SRCPATH)/memory_buffer_alloc.c                 \
			$(SRCPATH)/mps_reader.c                          \
			$(SRCPATH)/mps_trace.c                           \
			$(SRCPATH)/net_sockets.c                         \
			$(SRCPATH)/nist_kw.c                             \
			$(SRCPATH)/oid.c                                 \
			$(SRCPATH)/padlock.c                             \
			$(SRCPATH)/pem.c                                 \
			$(SRCPATH)/pk.c                                  \
			$(SRCPATH)/pkcs12.c                              \
			$(SRCPATH)/pkcs5.c                               \
			$(SRCPATH)/pkcs7.c                               \
			$(SRCPATH)/pk_ecc.c                              \
			$(SRCPATH)/pkparse.c                             \
			$(SRCPATH)/pk_wrap.c                             \
			$(SRCPATH)/pkwrite.c                             \
			$(SRCPATH)/platform.c                            \
			$(SRCPATH)/platform_util.c                       \
			$(SRCPATH)/poly1305.c                            \
			$(SRCPATH)/psa_crypto_aead.c                     \
			$(SRCPATH)/psa_crypto.c                          \
			$(SRCPATH)/psa_crypto_cipher.c                   \
			$(SRCPATH)/psa_crypto_client.c                   \
			$(SRCPATH)/psa_crypto_driver_wrappers_no_static.c\
			$(SRCPATH)/psa_crypto_ecp.c                      \
			$(SRCPATH)/psa_crypto_ffdh.c                     \
			$(SRCPATH)/psa_crypto_hash.c                     \
			$(SRCPATH)/psa_crypto_mac.c                      \
			$(SRCPATH)/psa_crypto_pake.c                     \
			$(SRCPATH)/psa_crypto_rsa.c                      \
			$(SRCPATH)/psa_crypto_se.c                       \
			$(SRCPATH)/psa_crypto_slot_management.c          \
			$(SRCPATH)/psa_crypto_storage.c                  \
			$(SRCPATH)/psa_its_file.c                        \
			$(SRCPATH)/psa_util.c                            \
			$(SRCPATH)/ripemd160.c                           \
			$(SRCPATH)/rsa_alt_helpers.c                     \
			$(SRCPATH)/rsa.c                                 \
			$(SRCPATH)/sha1.c                                \
			$(SRCPATH)/sha256.c                              \
			$(SRCPATH)/sha3.c                                \
			$(SRCPATH)/sha512.c                              \
			$(SRCPATH)/ssl_cache.c                           \
			$(SRCPATH)/ssl_ciphersuites.c                    \
			$(SRCPATH)/ssl_client.c                          \
			$(SRCPATH)/ssl_cookie.c                          \
			$(SRCPATH)/ssl_debug_helpers_generated.c         \
			$(SRCPATH)/ssl_msg.c                             \
			$(SRCPATH)/ssl_ticket.c                          \
			$(SRCPATH)/ssl_tls12_client.c                    \
			$(SRCPATH)/ssl_tls12_server.c                    \
			$(SRCPATH)/ssl_tls13_client.c                    \
			$(SRCPATH)/ssl_tls13_generic.c                   \
			$(SRCPATH)/ssl_tls13_keys.c                      \
			$(SRCPATH)/ssl_tls13_server.c                    \
			$(SRCPATH)/ssl_tls.c                             \
			$(SRCPATH)/threading.c                           \
			$(SRCPATH)/timing.c                              \
			$(SRCPATH)/version.c                             \
			$(SRCPATH)/version_features.c                    \
			$(SRCPATH)/x509.c                                \
			$(SRCPATH)/x509_create.c                         \
			$(SRCPATH)/x509_crl.c                            \
			$(SRCPATH)/x509_crt.c                            \
			$(SRCPATH)/x509_csr.c                            \
			$(SRCPATH)/x509write.c                           \
			$(SRCPATH)/x509write_crt.c                       \
			$(SRCPATH)/x509write_csr.c                       \


MBEDTLS_CFLAGS += -Imbedtls-3.6.2/include
